---
debug: false
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data

logs:
  level: DEBUG
  token: ~

mongodb:
  authn: ~
  database: catalog_staging

pipelines:
  pipeline_uuid: ~
  pipeline_manager_id: kOYmxWRq5X4K7
  pipeline_manager_nonce: ~
  job_manager_id: MEzqaw4rkWZoK
  job_manager_nonce: SD2E_z00EbBOeoYJry
  job_indexer_id: Pw3eRxrqLZGmp
  job_indexer_nonce: SD2E_RyZRVDMgXK1DV
  process_uuid: 117a32a1-457c-5bfe-bded-ed0ca99e53f8
