---
debug: false
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data

logs:
  level: DEBUG
  token: ~

mongodb:
  authn: ~
  database: catalog_test

pipelines:
  pipeline_uuid: ~
  pipeline_manager_id: ~
  pipeline_manager_nonce: ~
  job_manager_id: MEzqaw4rkWZoK
  job_manager_nonce: SD2E_z00EbBOeoYJry
  job_indexer_id: Pw3eRxrqLZGmp
  job_indexer_nonce: SD2E_RyZRVDMgXK1DV
